Update the-edit-workflow.md
`jj new -B` now requires you to specify which commit you're inserting before.

When I used the original command, I got this message:

```
$ jj new -B -m "add more comments"
error: a value is required for '--insert-before <INSERT_BEFORE>' but none was supplied

For more information, try '--help'.
```