Quote author name
The argument to author() contains a space and needs to be quoted, otherwise
it produces an error (tested with jj 0.22.0):

❱ jj log -r 'author(Steve Klabnik) & description(print)'
Error: Failed to parse revset: Syntax error
Caused by:  --> 1:14
  |
1 | author(Steve Klabnik) & description(print)
  |              ^---
  |
  = expected `|`, `&`, or `~`